### ISSUE TITLE
无法全屏

### ISSUE THREAD

**Issue by nbaxiaolaodi** [myd510/VideoWallpaper#1]

**Comment by myd510** [comment]
You can try to replace sleep(0.1) with sleep(1), ffplaye needs some time to make the parameters take effect. if the example.py still doesn't work, try other player. I noticed this problem. I'll fixed this problem in about a month.

**Comment by myd510** [comment]
I fixed this problem, use "-x" and "-y" parameters to force ffplay to use screen resolution when create ffplay process.
